---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: nginx-source
  namespace: flux-system
spec:
  gitImplementation: go-git
  interval: 30s
  ref:
    branch: main
  timeout: 1m0s
  url: https://github.com/dimkatsi91/K8s_Lab.git

