---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx-staging
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./deploy/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: nginx-source
  targetNamespace: nginx-ns

